knpu_oauth2_client:
    clients:
        github:
            type: github
            client_id: '%env(CLIENT_ID)%'
            client_secret: '%env(CLIENT_SECRET)%'
            redirect_route: connect_github_check